spring:
  profiles:
    active: dev


---

spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8000

---

spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8001
